name: Suggest a Prompt
description: Suggest a new AI prompt to be added to the collection.
title: "[PROMPT] <Short description of prompt>"
labels: ["New Prompt Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new prompt! Please fill out the details below.
  
  - type: dropdown
    id: prompt-type
    attributes:
      label: Prompt Type
      description: Is this a text-based prompt or a JSON structured prompt?
      options:
        - Text
        - JSON
    validations:
      required: true

  - type: dropdown
    id: has-reference
    attributes:
      label: Can it be used with a reference image?
      description: Does this prompt support uploading a user face/style reference?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  


  - type: textarea
    id: generic-prompt
    attributes:
      label: Generic Prompt
      description: The standard prompt text (used when "Generic Prompt" tab is active).
      render: json
    validations:
      required: true

  - type: textarea
    id: reference-prompt
    attributes:
      label: Reference Prompt (If applicable)
      description: The full prompt text to be used when "Using Reference Photo" is active. Typically contains "Use the uploaded reference image..."
      placeholder: "Use the uploaded reference image as..."
      render: json
    validations:
      required: false

  - type: input
    id: image-url
    attributes:
      label: Example Image URL (Optional)
      description: Link to an example result image.
    validations:
      required: false
